/// Maps each Pro Sports category to the top 10 most popular team names.
/// Used in onboarding to let users pick their favorite team from a list
/// instead of free-text input.
const Map<String, List<String>> sportsTeams = {
  'Football': [
    'Dallas Cowboys',
    'New England Patriots',
    'Green Bay Packers',
    'Pittsburgh Steelers',
    'San Francisco 49ers',
    'Kansas City Chiefs',
    'Philadelphia Eagles',
    'Chicago Bears',
    'New York Giants',
    'Las Vegas Raiders',
  ],
  'Basketball': [
    'Los Angeles Lakers',
    'Golden State Warriors',
    'Chicago Bulls',
    'Boston Celtics',
    'Miami Heat',
    'New York Knicks',
    'Brooklyn Nets',
    'San Antonio Spurs',
    'Philadelphia 76ers',
    'Dallas Mavericks',
  ],
  'Baseball': [
    'New York Yankees',
    'Los Angeles Dodgers',
    'Boston Red Sox',
    'Chicago Cubs',
    'St. Louis Cardinals',
    'San Francisco Giants',
    'Atlanta Braves',
    'Houston Astros',
    'New York Mets',
    'Philadelphia Phillies',
  ],
  'Soccer': [
    'Real Madrid',
    'FC Barcelona',
    'Manchester United',
    'Liverpool FC',
    'Bayern Munich',
    'Paris Saint-Germain',
    'Manchester City',
    'Juventus',
    'Chelsea FC',
    'Arsenal FC',
  ],
  'Tennis': [
    'Team Djokovic',
    'Team Alcaraz',
    'Team Sinner',
    'Team Nadal',
    'Team Federer',
    'Team Swiatek',
    'Team Gauff',
    'Team Sabalenka',
    'Team Medvedev',
    'Team Rune',
  ],
  'Golf': [
    'Team Scheffler',
    'Team McIlroy',
    'Team Rahm',
    'Team Koepka',
    'Team DeChambeau',
    'Team Spieth',
    'Team Thomas',
    'Team Hovland',
    'Team Morikawa',
    'Team Clark',
  ],
};
